FROM python:3.8

ADD ./requirements.txt /requirements.txt
RUN pip3 install -r requirements.txt
RUN rm -rf requirements.txt
RUN apt-get install uwsgi-core -y
RUN apt-get install uwsgi-plugin-python3 -y

WORKDIR /

RUN useradd deployer
RUN chown deployer:deployer /app/tmp

ADD ./app /app

ADD ./conf/uwsgi/uwsgi.ini /etc/uwsgi/apps-available
ADD ./conf/nginx/uwsgi.conf /etc/nginx/sites-available

#remove soft-link
RUN rm -rf /etc/uwsgi/apps-enabled/*
RUN rm -rf /etc/nginx/apps-enabled/*

RUN ln -s /etc/uwsgi/apps-available/uwsgi.ini /etc/uwsgi/app-enabled/uwsgi.ini
RUN ln -s /etc/nginx/apps-available/nginx.conf /etc/nginx/apps-enabled/nginx.conf

RUN 